name: DODo

on:
 workflow_dispatch:
 
jobs:
  ArgoCLI:
    runs-on: ubuntu-latest
    steps: 
    - uses: clowdhaus/argo-cd-action/@main
      with:
        version: 2.5.5
    
    - name: login
      shell: bash
      run: | 
       KEY=${{ secrets.ARGOCD_SERVER }}
       echo $KEY
      
  
  
